-- AlterTable
ALTER TABLE "Todo" ADD COLUMN "createdAt" DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Todo" ADD COLUMN "done" BOOLEAN DEFAULT false;
ALTER TABLE "Todo" ADD COLUMN "updatedAt" DATETIME;
